version: '3'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    command: --bind_ip 0.0.0.0
    env_file:
      - .env
    volumes:
      - mongodbdata:/data/db
      - mongodbdata:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      default:
        ipv4_address: ${MONGO_IP}
  dns:
    build: ./dns
    image: docker_dns
    container_name: dns
    env_file:
      - .env
    volumes:
      - ./dns:/mnt/dns
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "53/udp"
    networks:
      default:
        ipv4_address: ${DNS_IP}
  rtpengine:
    build: ./rtpengine
    image: docker_rtpengine
    container_name: rtpengine
    privileged: true
    env_file:
      - .env
    volumes:
      - ./rtpengine:/mnt/rtpengine
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    environment:
      - TABLE=0
      - INTERFACE=${RTPENGINE_IP}
      - LISTEN_NG=${RTPENGINE_IP}:2223
      - PIDFILE=/run/ngcp-rtpengine-daemon.pid
      - PORT_MAX=50000
      - PORT_MIN=49000
      - NO_FALLBACK=no
      - TOS=184
    expose:
      - "2223/udp"
      - "49000-50000/udp"
    networks:
      default:
        ipv4_address: ${RTPENGINE_IP}
  mysql:
    build: ./mysql
    image: docker_mysql
    container_name: mysql
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3306/tcp"
    networks:
      default:
        ipv4_address: ${MYSQL_IP}
  pyhss:
    build: ./pyhss
    image: docker_pyhss
    container_name: pyhss
    dns: ${DNS_IP}
    volumes:
      - ./pyhss:/mnt/pyhss
      - ./pyhss/logs:/pyhss/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - dns
      - mysql
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "8080/tcp"
    ports:
      - "8080:8080/tcp"
    networks:
      default:
        ipv4_address: ${PYHSS_IP}

        

  niralos-nrf-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9090:9090
    command: >-
      bin/bash -c "./install/bin/niralos-nrfd -c /niral_config/yaml/nrf.yaml -l
      /niral_config/log/nrf.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
    restart: always
  niralos-scp-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9091:9090
    command: >-
      bin/bash -c "sleep 10;./install/bin/niralos-scpd -c
      /niral_config/yaml/scp.yaml -l /niral_config/log/scp.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
    restart: always
  niralos-udr-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9092:9090
    command: >-
      bin/bash -c "sleep 20; ./install/bin/niralos-udrd -c
      /niral_config/yaml/udr.yaml -l /niral_config/log/udr.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
    restart: always
  niralos-udm-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9093:9090
    command: >-
      bin/bash -c "sleep 20; ./install/bin/niralos-udmd -c
      /niral_config/yaml/udm.yaml -l /niral_config/log/udm.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
    restart: always
  niralos-ausf-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9094:9090
    command: >-
      bin/bash -c "sleep 20; ./install/bin/niralos-ausfd -c
      /niral_config/yaml/ausf.yaml -l /niral_config/log/ausf.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
    restart: always
  niralos-pcf-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9095:9090
    command: >-
      bin/bash -c "sleep 20; ./install/bin/niralos-pcfd -c
      /niral_config/yaml/pcf.yaml -l /niral_config/log/pcf.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
    restart: always
  niralos-bsf-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9096:9090
    command: >-
      bin/bash -c "sleep 20; ./install/bin/niralos-bsfd -c
      /niral_config/yaml/bsf.yaml -l /niral_config/log/bsf.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
    restart: always
  niralos-nssf-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9097:9090
    command: >-
      bin/bash -c "sleep 20; ./install/bin/niralos-nssfd -c
      /niral_config/yaml/nssf.yaml -l /niral_config/log/nssf.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
    restart: always
  niralos-amf-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9098:9090
    command: >-
      bin/bash -c "sleep 20; ./install/bin/niralos-amfd -c
      /niral_config/yaml/amf.yaml -l /niral_config/log/amf.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
      # niralos-ngap-gtpu:
      #   ipv4_address: 10.228.17.12
    restart: always
  niralos-smf-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9099:9090
    command: >-
      bin/bash -c "sleep 20; ./install/bin/niralos-smfd -c
      /niral_config/yaml/smf.yaml -l /niral_config/log/smf.log"
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
    restart: always
  niralos-upf-1:
    image: niralnetworks/niralos-5g-core:2.2.3
    ports:
      - 9100:9090
    privileged: true
    command: >-
      bin/bash -c "sleep 20; ip tuntap add name niralos-gw mode tun ; ip addr
      add 10.101.0.1/16 dev niralos-gw ; sysctl -w
      net.ipv6.conf.all.disable_ipv6=1 ; ip link set niralos-gw up ; sh -c
      \"echo 1 > /proc/sys/net/ipv4/ip_forward\" ; iptables -t nat -A
      POSTROUTING -s 10.101.0.0/16 -p all -j MASQUERADE ; route add
      default gw 10.228.17.1 ; sleep 20 ; ./install/bin/niralos-upfd -c
      /niral_config/yaml/upf.yaml -l /niral_config/log/upf.log "
    volumes:
      - /home/anurag/niral_config:/niral_config
    networks:
      niralos-mesh: null
      # niralos-ngap-gtpu:
      #   ipv4_address: 10.228.17.13
    restart: always



        
  icscf:
    image: docker_kamailio
    container_name: icscf
    dns: ${DNS_IP}
    volumes:
      - ./icscf:/mnt/icscf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=icscf-1
    depends_on:
      - dns
      - mysql
      - pyhss
    expose:
      - "3869/udp"
      - "3869/tcp"
      - "4060/udp"
      - "4060/tcp"
    networks:
      default:
        ipv4_address: ${ICSCF_IP}
  scscf:
    image: docker_kamailio
    container_name: scscf
    dns: ${DNS_IP}
    volumes:
      - ./scscf:/mnt/scscf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=scscf-1
    depends_on:
      - dns
      - mysql
      - pyhss
    expose:
      - "3870/udp"
      - "3870/tcp"
      - "6060/udp"
      - "6060/tcp"
    networks:
      default:
        ipv4_address: ${SCSCF_IP}
  pcscf:
    image: docker_kamailio
    container_name: pcscf
    dns: ${DNS_IP}
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pcscf:/mnt/pcscf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=pcscf-1
      - DEPLOY_MODE=5G
    depends_on:
      - dns
      - mysql
      - rtpengine
      - icscf
      - scscf
    expose:
      - "3871/udp"
      - "3871/tcp"
      - "5060/tcp"
      - "5060/udp"
      - "5100-5120/tcp"
      - "5100-5120/udp"
      - "6100-6120/tcp"
      - "6100-6120/udp"
    networks:
      default:
        ipv4_address: ${PCSCF_IP}
  smsc:
    image: docker_kamailio
    container_name: smsc
    dns: ${DNS_IP}
    volumes:
      - ./smsc:/mnt/smsc
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=smsc-1
    depends_on:
      - dns
      - mysql
    expose:
      - "7090/udp"
      - "7090/tcp"
    networks:
      default:
        ipv4_address: ${SMSC_IP}
networks:
  default:
    ipam:
      config:
        - subnet: ${TEST_NETWORK}
  niralos-ngap-gtpu:
    name: niralos-ngap-gtpu
    external: true      
volumes:
  mongodbdata: {}
  dbdata: {}
